Repository mchartigan/bitwise, pull requests merged in 2020-10, with the labels that each got.

#18 Account info integration
  public/account.html
  public/index.html
  public/js/account.js
  public/js/index.js
  public/profile.html
Labels: enhancement, user story

#21 Posting
  public/common/create_post.html
  public/common/login.html
  public/index.html
  public/js/create_post.js
  public/js/index.js
  public/js/login.js
Labels: enhancement, user story

#22 Fix 'account.js' folder reference error
  public/common/account.html
Labels: bug

#24 Fix userline merge issues
  public/common/create_post.html
  public/common/profile.html
  public/index.html
  public/js/profile.js
Labels: bug

#25 Homepage cleanup
  public/common/account.html
  public/common/login.html
  public/js/account.js
  public/js/index.js
  public/js/login.js
Labels: bug

#27 Demo cleanup
  public/common/account.html
  public/common/create_post.html
  public/common/login.html
  public/common/profile.html
  public/index.html
  public/js/account.js
  public/js/create_post.js
  public/js/index.js
  public/js/login.js
  public/js/profile.js
Labels: bug, enhancement

#28 changed post appearance slightly, deleted profile-stylescss
  public/css/profile-styles.css
  public/css/styles.css
  public/js/index.js
  public/js/profile.js
Labels: enhancement

#29 Profile information now checks for a unique username when a user attempts to change it
  public/js/account.js
Labels: user story

#32 Basic comments
  public/common/test.html
  public/index.html
  public/js/create_post.js
  public/js/post.js
  public/js/test.js
Labels: enhancement, user story

#34 Save user information on anonymous posts for server side use
  public/js/create_post.js
  public/js/index.js
Labels: enhancement, user story
